sonar.projectKey=mquelas_final-ing-soft-3
sonar.organization=mquelas
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.exclusions=**/*.spec.ts,frontend/src/test.ts
sonar.test.inclusions=frontend/src/**/*.spec.ts
sonar.coverage.exclusions=backend/app/config.py,backend/app/main.py,backend/app/routes/admin_users.py,backend/app/routes/auth.py,backend/app/routes/company_user.py,backend/app/services.py,frontend/src/environments/**,frontend/src/main.ts,frontend/src/styles.css,frontend/src/app/**/*.ts
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
